#pragma once
//PLANTS*************
#define PLANT_INITIATIVE 0
#define SOWING_DISTANCE 1
//GRASS
#define GRASS_STRENGTH 0
#define GRASS_SYMBOL '#'
//DEADLY NIGHTSHADE
#define DEADLY_NIGHTSHADE_STRENGTH 99
#define DEADLY_NIGHTSHADE_SYMBOL 'x'

//TODO DODAÆ DO S£OWNIKA